/*
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type OAuth2Client struct {

	// ClientID  is the id for this client.
	ClientId string `json:"client_id,omitempty"`

	// Secret is the client's secret. The secret will be included in the create request as cleartext, and then never again. The secret is stored using BCrypt so it is impossible to recover it. Tell your users that they need to write the secret down as it will not be made available again.
	ClientSecret string `json:"client_secret,omitempty"`

	// Name is the human-readable string name of the client to be presented to the end-user during authorization.
	ClientName string `json:"client_name,omitempty"`

	// GrantTypes is an array of grant types the client is allowed to use.
	// Public Client 必須是 [“implicit”].
	// Confidential Client 必須是 [“urn:ietf:params:oauth:grant-type:token-exchange”].
	GrantTypes []string `json:"grant_types,omitempty"`

	// ClientURI is an URL string of a web page providing information about the client. If present, the server SHOULD display this URL to the end-user in a clickable fashion.
	ClientUri string `json:"client_uri,omitempty"`

	// Contacts is a array of strings representing ways to contact people responsible for this client, typically email addresses.
	Contacts []string `json:"contacts,omitempty"`

	// A unique identifier string to identify the client software to be dynamically registered.
	SoftwareId string `json:"software_id"`

	// A version identifier string for the client software identified by “software_id”.
	SoftwareVersion string `json:"software_version"`

	// Resource Sets
	ResourceSets []string `json:"resource_sets"`

	// RedirectURIs is an array of allowed redirect urls for the client, for example http://mydomain/oauth/callback .
	RedirectUris []string `json:"redirect_uris,omitempty"`

	// ResponseTypes is an array of the OAuth 2.0 response type strings that the client can use at the authorization endpoint.
	// Public Client 必須是 [“token”, "id_token"].
	ResponseTypes []string `json:"response_types,omitempty"`

	IdTokenSignedResponseAlg string `json:"id_token_signed_response_alg,omitempty"`

	RequestObjectSigningAlg string `json:"request_object_signing_alg,omitempty"`

	// Client’s JWKS document value, which contains the client’s public keys.
	Jwks *JsonWebKeySet `json:"jwks,omitempty"`

	// Requested Client Authentication method for the Token Endpoint. The options are client_secret_post, client_secret_basic, private_key_jwt, and none.
	// Confidential Client: 必須是 "private_key_jwt"
	TokenEndpointAuthMethod string `json:"token_endpoint_auth_method,omitempty"`
}
