###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://ory-am.gitbooks.io/hydra/content/tutorial.html                 #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

version: '2'

services:

  hydra-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgresd:postgresd
    environment:
      - LOG_LEVEL=debug
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
    command:
      migrate sql -e
    restart: on-failure

  hydra-admin:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgresd:postgresd
#     Uncomment the following line to use mysql instead.
#      - mysqld:mysqld
    depends_on:
      - hydra-migrate
    ports:
      - "4445:4445"
    command:
      serve admin --dangerous-force-http
    environment:
      - LOG_LEVEL=debug
      - OAUTH2_ISSUER_URL=http://localhost:4444
      - OAUTH2_CONSENT_URL=http://localhost:3000/consent
      - OAUTH2_LOGIN_URL=http://localhost:4200/login
      - OAUTH2_LOGOUT_REDIRECT_URL=http://localhost:4200/logout-callback
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
#     Uncomment the following line to use mysql instead.
#      - DATABASE_URL=mysql://root:secret@tcp(mysqld:3306)/mysql?parseTime=true
      - SYSTEM_SECRET=youReallyNeedToChangeThis
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - OAUTH2_ACCESS_TOKEN_STRATEGY=jwt
      - DISABLE_CONSENT_FLOW=1
      - BY_PASS_ROUTES=/clients
      - CORS_ENABLED=1
      - CORP_INTERNAL_API_URL=http://mock-dep:8080
      - AD_LOGIN_URL=http://mock-dep:8080/ad/login
    restart: on-failure

  hydra:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgresd:postgresd
#     Uncomment the following line to use mysql instead.
#      - mysqld:mysqld
    depends_on:
      - hydra-migrate
    ports:
      - "4444:4444"
    command:
      serve public --dangerous-force-http
    environment:
      - LOG_LEVEL=debug
      - OAUTH2_ISSUER_URL=http://localhost:4444
      - OAUTH2_CONSENT_URL=http://localhost:3000/consent
      - OAUTH2_LOGIN_URL=http://localhost:4200/login
      - OAUTH2_LOGOUT_REDIRECT_URL=http://localhost:4200/logout-callback
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
#     Uncomment the following line to use mysql instead.
#      - DATABASE_URL=mysql://root:secret@tcp(mysqld:3306)/mysql?parseTime=true
      - SYSTEM_SECRET=youReallyNeedToChangeThis
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - OAUTH2_ACCESS_TOKEN_STRATEGY=jwt
      - DISABLE_CONSENT_FLOW=1
      - BY_PASS_ROUTES=/clients,/forgot-password,/reset-password
      - CORS_ENABLED=1
      - CORP_INTERNAL_API_URL=http://mock-dep:8080
      - AD_LOGIN_URL=http://mock-dep:8080/ad/login
      - GRAPHQL_API_URL=http://mbs:4000
      - EMAIL_SERVICE_URL=http://mta:10025
    restart: on-failure

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra-admin:4445
    image: oryd/hydra-login-consent-node:v1.0.0-beta.9
    links:
      - hydra-admin
    ports:
      - "3000:3000"
    restart: on-failure

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra

#  Uncomment the following section to use mysql instead.
#  mysqld:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=secret

  mock-dep:
    image: ekino/wiremock:latest
    ports:
      - 8080:8080
    volumes:
      - "./mock-dep/__files:/wiremock/__files"
      - "./mock-dep/mappings:/wiremock/mappings"

  mta:
    image: mta:latest
    ports:
      - 10025:10025
    environment:
      - SENDERS=FIXME
      - AWS_REGION=FIXME
      - AWS_ACCESS_KEY_ID=FIXME
      - AWS_SECRET_ACCESS_KEY=FIXME
